In [2]:
import numpy as np
import gurobipy as gp
import pandas as pd

# Question 3

In [45]:
df1 = pd.read_csv('roi_mat.csv', index_col = ['Unnamed: 0'])
df1 = df1/100
df1

Print     TV    SEO  AdWords  Facebook  LinkedIn  Instagram  \
January    0.040  0.036  0.024    0.039     0.030     0.035      0.036   
February   0.040  0.039  0.027    0.038     0.043     0.032      0.027   
March      0.035  0.029  0.031    0.038     0.024     0.041      0.037   
April      0.038  0.031  0.024    0.044     0.024     0.038      0.037   
May        0.035  0.032  0.019    0.034     0.027     0.027      0.039   
June       0.040  0.032  0.027    0.034     0.034     0.030      0.045   
July       0.039  0.036  0.020    0.044     0.039     0.037      0.043   
August     0.042  0.033  0.028    0.042     0.020     0.037      0.036   
September  0.041  0.028  0.025    0.042     0.029     0.037      0.028   
October    0.030  0.030  0.031    0.046     0.031     0.033      0.032   
November   0.048  0.033  0.027    0.041     0.029     0.036      0.042   
December   0.048  0.040  0.019    0.037     0.042     0.036      0.026   

           Snapchat  Twitter  Email  
January      0.0225    0.035  0.035  
February     0.0180    0.037  0.035  
March        0.0260    0.042  0.025  
April        0.0250    0.036  0.029  
May          0.0220    0.045  0.039  
June         0.0210    0.038  0.041  
July         0.0180    0.040  0.038  
August       0.0150    0.044  0.043  
September    0.0250    0.040  0.034  
October      0.0230    0.025  0.032  
November     0.0300    0.031  0.041  
December     0.0290    0.036  0.037

In [3]:
df = pd.read_csv('ROI_data.csv')

In [29]:
obj = np.array([.031, .049, .024, .039, .016, .024, .046, .026, .033, .044]) # objective vector
A = np.zeros((13,10)) 
A[0,:] = [1,1,1,1,1,1,1,1,1,1] 
A[1,:] = [1,0,0,0,0,0,0,0,0,0] 
A[2,:] = [0,1,0,0,0,0,0,0,0,0] 
A[3,:] = [0,0,1,0,0,0,0,0,0,0] 
A[4,:] = [0,0,0,1,0,0,0,0,0,0] 
A[5,:] = [0,0,0,0,1,0,0,0,0,0] 
A[6,:] = [0,0,0,0,0,1,0,0,0,0] 
A[7,:] = [0,0,0,0,0,0,1,0,0,0] 
A[8,:] = [0,0,0,0,0,0,0,1,0,0] 
A[9,:] = [0,0,0,0,0,0,0,0,1,0] 
A[10,:] = [0,0,0,0,0,0,0,0,0,1] 
A[11,:] = [1,1,0,0,-1,0,0,0,0,-1] 
A[12,:] = [0,0,2,2,-1,-1,-1,-1,-1,0] 

b = np.array([10,3,3,3,3,3,3,3,3,3,3,0,0]) 
sense = np.array(['<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<']) 

In [30]:
ojModel = gp.Model() 
ojModX = ojModel.addMVar(10)
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b)
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)
ojModel.Params.OutputFlag = 0 

In [31]:
ojModel.optimize()

In [32]:
ojModel.objVal

0.45600000000000007

In [33]:
ojModX.x

array([0., 3., 0., 1., 0., 0., 3., 0., 0., 3.])

In [35]:
allocation = ojModX.x
allocation

array([0., 3., 0., 1., 0., 0., 3., 0., 0., 3.])

# Question 4

In [61]:
obj = np.array([.049, .023, .024, .039, .044, .046, .026, .019, .037, .026]) # objective vector
A = np.zeros((13,10)) 
A[0,:] = [1,1,1,1,1,1,1,1,1,1] 
A[1,:] = [1,0,0,0,0,0,0,0,0,0] 
A[2,:] = [0,1,0,0,0,0,0,0,0,0] 
A[3,:] = [0,0,1,0,0,0,0,0,0,0] 
A[4,:] = [0,0,0,1,0,0,0,0,0,0] 
A[5,:] = [0,0,0,0,1,0,0,0,0,0] 
A[6,:] = [0,0,0,0,0,1,0,0,0,0] 
A[7,:] = [0,0,0,0,0,0,1,0,0,0] 
A[8,:] = [0,0,0,0,0,0,0,1,0,0] 
A[9,:] = [0,0,0,0,0,0,0,0,1,0] 
A[10,:] = [0,0,0,0,0,0,0,0,0,1] 
A[11,:] = [1,1,0,0,-1,0,0,0,0,-1] 
A[12,:] = [0,0,2,2,-1,-1,-1,-1,-1,0] 

b = np.array([10,3,3,3,3,3,3,3,3,3,3,0,0]) 
sense = np.array(['<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<']) 

In [62]:
ojModel = gp.Model() 
ojModX = ojModel.addMVar(10)
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b)
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)
ojModel.Params.OutputFlag = 0 

In [63]:
ojModel.optimize()

In [64]:
ojModel.objVal

0.45600000000000007

In [65]:
ojModX.x

array([3., 0., 0., 1., 3., 3., 0., 0., 0., 0.])

# Question 5

In [ ]:
Yes, the allocations are same. Lower by 0.252 and 0.264

Constraint 3 is useful only if we want to minimize risk and we have uncertainty regarding whether the ROI data we are
utilizing is correct or not

In [66]:
obj = np.array([.049, .023, .024, .039, .044, .046, .026, .019, .037, .026]) # objective vector
A = np.zeros((13,10)) 
A[0,:] = [1,1,1,1,1,1,1,1,1,1] 
A[1,:] = [1,0,0,0,0,0,0,0,0,0] 
A[2,:] = [0,1,0,0,0,0,0,0,0,0] 
A[3,:] = [0,0,1,0,0,0,0,0,0,0] 
A[4,:] = [0,0,0,1,0,0,0,0,0,0] 
A[5,:] = [0,0,0,0,1,0,0,0,0,0] 
A[6,:] = [0,0,0,0,0,1,0,0,0,0]  
A[7,:] = [0,0,0,0,0,0,1,0,0,0] 
A[8,:] = [0,0,0,0,0,0,0,1,0,0] 
A[9,:] = [0,0,0,0,0,0,0,0,1,0] 
A[10,:] = [0,0,0,0,0,0,0,0,0,1] 
A[11,:] = [1,1,0,0,-1,0,0,0,0,-1] 
A[12,:] = [0,0,2,2,-1,-1,-1,-1,-1,0] 

b = np.array([10,10,10,10,10,10,10,10,10,10,10,0,0]) 
sense = np.array(['<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<']) 

In [67]:
ojModel = gp.Model() 
ojModX = ojModel.addMVar(10)
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b)
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)
ojModel.Params.OutputFlag = 0 

In [68]:
ojModel.optimize()

In [69]:
ojModel.objVal

0.46499999999999997

In [70]:
ojModX.x

array([5., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [71]:
obj = np.array([.031, .049, .024, .039, .016, .024, .046, .026, .033, .044]) # objective vector
A = np.zeros((13,10)) 
A[0,:] = [1,1,1,1,1,1,1,1,1,1] 
A[1,:] = [1,0,0,0,0,0,0,0,0,0] 
A[2,:] = [0,1,0,0,0,0,0,0,0,0] 
A[3,:] = [0,0,1,0,0,0,0,0,0,0] 
A[4,:] = [0,0,0,1,0,0,0,0,0,0] 
A[5,:] = [0,0,0,0,1,0,0,0,0,0] 
A[6,:] = [0,0,0,0,0,1,0,0,0,0] 
A[7,:] = [0,0,0,0,0,0,1,0,0,0] 
A[8,:] = [0,0,0,0,0,0,0,1,0,0] 
A[9,:] = [0,0,0,0,0,0,0,0,1,0] 
A[10,:] = [0,0,0,0,0,0,0,0,0,1] 
A[11,:] = [1,1,0,0,-1,0,0,0,0,-1] 
A[12,:] = [0,0,2,2,-1,-1,-1,-1,-1,0] 

b = np.array([10,10,10,10,10,10,10,10,10,10,10,0,0]) 
sense = np.array(['<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<']) 

In [72]:
ojModel = gp.Model() 
ojModX = ojModel.addMVar(10)
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b)
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)
ojModel.Params.OutputFlag = 0 

In [73]:
ojModel.optimize()

In [74]:
ojModel.objVal

0.46499999999999997

In [75]:
ojModX.x

array([0., 5., 0., 0., 0., 0., 0., 0., 0., 5.])

# Question 6 

In [39]:
roi = pd.DataFrame(data = np.zeros((10,2)), columns = ['min_roi', 'max_roi'], index = df.iloc[0, 1:].index)

A = np.zeros((13,10)) 
A[0,:] = [1,1,1,1,1,1,1,1,1,1] 
A[1,:] = [1,0,0,0,0,0,0,0,0,0] 
A[2,:] = [0,1,0,0,0,0,0,0,0,0] 
A[3,:] = [0,0,1,0,0,0,0,0,0,0] 
A[4,:] = [0,0,0,1,0,0,0,0,0,0] 
A[5,:] = [0,0,0,0,1,0,0,0,0,0] 
A[6,:] = [0,0,0,0,0,1,0,0,0,0] 
A[7,:] = [0,0,0,0,0,0,1,0,0,0] 
A[8,:] = [0,0,0,0,0,0,0,1,0,0] 
A[9,:] = [0,0,0,0,0,0,0,0,1,0] 
A[10,:] = [0,0,0,0,0,0,0,0,0,1] 
A[11,:] = [1,1,0,0,-1,0,0,0,0,-1] 
A[12,:] = [0,0,2,2,-1,-1,-1,-1,-1,0] 

b = np.array([10,3,3,3,3,3,3,3,3,3,3,0,0]) 
sense = np.array(['<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<']) 

for i in range(10):

    for idx in range(1, 501, 1):

        change = idx/1000

        obj = np.array(df.iloc[0, 1:]) # objective vector
        obj[i] = obj[i] + change

        ojModel = gp.Model()

        ojModX = ojModel.addMVar(len(obj))

        ojModCon = ojModel.addMConstrs(A, ojModX, sense, b)
        ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)

        ojModel.Params.OutputFlag = 0
        ojModel.optimize() # solve the LP
        
        if not np.all(ojModX.x == allocation):
            break
        else: 
            max_roi = obj[i]
    
    for idx in range(1, 101, 1):

        change = idx/1000

        obj = np.array(df.iloc[0, 1:]) # objective vector
        obj[i] = obj[i] - change

        ojModel = gp.Model()

        ojModX = ojModel.addMVar(len(obj))

        ojModCon = ojModel.addMConstrs(A, ojModX, sense, b)
        ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)

        ojModel.Params.OutputFlag = 0
        ojModel.optimize() # solve the LP
        
        if (not np.all(ojModX.x == allocation)) | (obj[i] < 0):
            break
        else:
            min_roi = round(obj[i], 3)
            
    roi.iloc[i,:] = [min_roi, max_roi]
    
roi['original'] = df.iloc[0, 1:]
roi

min_roi  max_roi original
Print        0.000    0.048    0.031
TV           0.039    0.549    0.049
SEO          0.000    0.039    0.024
AdWords      0.034    0.045    0.039
Facebook     0.000    0.038    0.016
LinkedIn     0.000    0.038    0.024
Instagram    0.040    0.546    0.046
Snapchat     0.000    0.039    0.026
Twitter      0.000    0.038    0.033
Email        0.029    0.544    0.044

# Question 7

In [47]:
budget = 10
allocation = []

for i in range(12):
    obj = np.array(df1.iloc[i])
    b = np.array([budget,3,3,3,3,3,3,3,3,3,3,0,0])
    sense = np.array(['<','<','<','<','<','<','<','<','<','<','<','<','<'])
    ojModel = gp.Model()

    ojModX = ojModel.addMVar(10)
    ojModCon = ojModel.addMConstrs(A, ojModX, sense, b)
    ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)

    ojModel.Params.OutputFlag = 0
    ojModel.optimize()
    ojModel.objVal
    allocation.append(ojModX.x)
    ror = (ojModel.objVal*0.5)
    budget = budget + ror
    
months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
opt_allocation = pd.DataFrame(allocation, index=months, columns=df.columns[1:] )
opt_allocation

Print   TV  SEO   AdWords  Facebook  LinkedIn  Instagram  Snapchat  \
Jan  3.000000  0.0  0.0  1.333333  0.000000  0.000000   2.666667       0.0   
Feb  3.000000  0.0  0.0  2.395500  3.000000  0.000000   0.000000       0.0   
Mar  0.000000  0.0  0.0  3.000000  0.000000  3.000000   1.389648       0.0   
Apr  0.000000  0.0  0.0  3.000000  0.000000  3.000000   3.000000       0.0   
May  1.804100  0.0  0.0  0.000000  0.000000  0.000000   3.000000       0.0   
Jun  3.000000  0.0  0.0  0.000000  0.000000  0.000000   3.000000       0.0   
Jul  1.123777  0.0  0.0  3.000000  1.123777  0.000000   3.000000       0.0   
Aug  3.000000  0.0  0.0  1.827294  0.000000  0.654588   0.000000       0.0   
Sep  1.362933  0.0  0.0  3.000000  0.000000  3.000000   0.000000       0.0   
Oct  0.000000  0.0  0.0  3.000000  0.000000  3.000000   3.000000       0.0   
Nov  3.000000  0.0  0.0  2.056421  0.000000  1.112842   3.000000       0.0   
Dec  3.000000  3.0  0.0  0.427951  3.000000  0.000000   0.000000       0.0   

      Twitter     Email  
Jan  0.000000  3.000000  
Feb  1.791000  0.000000  
Mar  3.000000  0.000000  
Apr  1.596856  0.000000  
May  3.000000  3.000000  
Jun  2.020172  3.000000  
Jul  3.000000  0.000000  
Aug  3.000000  3.000000  
Sep  3.000000  1.362933  
Oct  0.000000  2.955475  
Nov  0.000000  3.000000  
Dec  0.000000  3.000000

# Question 8